# Generated by Django 3.2.15 on 2022-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosempresa',
            name='ruc',
            field=models.CharField(max_length=20),
        ),
    ]
