# Generated by Django 3.2.15 on 2022-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0002_alter_datosempresa_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempresa',
            name='creacion_datos',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
    ]
