# Generated by Django 3.2.15 on 2022-08-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sri', '0003_auto_20220804_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosempresa',
            name='creacion_datos',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='creacion',
        ),
    ]
